# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcPWDcpp <- function(x, y) {
    .Call(fastLink_calcPWDcpp, x, y)
}

m_func_par <- function(temp, ptemp, natemp, limit1, limit2, nlim1, nlim2, ind, listid, matchesLink = FALSE, threads = 1L) {
    .Call(fastLink_m_func_par, temp, ptemp, natemp, limit1, limit2, nlim1, nlim2, ind, listid, matchesLink, threads)
}

