# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_index <- function(nA, nB) {
    .Call(fastLink_sample_index, nA, nB)
}

update_theta_svb <- function(nA_pair, nB_pair, psiA, psiB, theta_old, theta_prior, maxQ, nA, nB, iter, a_step, b_step, kappa_step) {
    .Call(fastLink_update_theta_svb, nA_pair, nB_pair, psiA, psiB, theta_old, theta_prior, maxQ, nA, nB, iter, a_step, b_step, kappa_step)
}

m_func_par <- function(temp, ptemp, natemp, limit1, limit2, nlim1, nlim2, ind, listid, matchesLink = FALSE, threads = 1L) {
    .Call(fastLink_m_func_par, temp, ptemp, natemp, limit1, limit2, nlim1, nlim2, ind, listid, matchesLink, threads)
}

